[package]
name = "komodo"
version = "0.3.0"
edition = "2021"

[features]
repl = [ "rustyline" ]

[dependencies]
codespan-reporting = "0.11.1"
pretty_assertions = "1.4.1"
rug = "1.26.1"
rustyline = { version = "14.0.0", optional = true }
unindent = "0.2.3"
