[package]
name = "symstatic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.4.3"
codespan-reporting = "0.11.1"
num-bigint = "0.4.5"
num-rational = "0.4.2"
rustyline = "14.0.0"
