[package]
name = "komodo"
version = "0.2.1"
edition = "2021"

[features]
repl = [ "rustyline" ]

[dependencies]
bigdecimal = "0.4.6"
codespan-reporting = "0.11.1"
num-bigint = "0.4.5"
num-rational = "0.4.2"
rustyline = { version = "14.0.0", optional = true }
unindent = "0.2.3"
