name: Interpreter Browser Port Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Run All Tests
        run: devenv shell ./go test-core-browser
