name: Interpreter Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
 run:
  working-directory: ./core

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy --all-targets --all-features
    - name: Run Unit Tests
      run: cargo test --verbose
    - name: Run e2e Tests
      run: sh interpreter-e2e-tests.sh
